# Dependencies
FROM node:21-alpine3.19 as deps

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install




# Builder - Construye la aplicación
FROM node:21-alpine3.19 as build

WORKDIR /usr/src/app

# Copiar de deps, los módulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules

# Copiar todo el código fuente de la aplicación
COPY . .

# RUN npm run test
RUN npm run build

RUN npm ci -f --only=production && npm cache clean --force




# Crear la imagen final de docker
FROM node:21-alpine3.19 as prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist

# opcional
ENV NODE_ENV=production

# para que no tenga todos los permisos
USER node

EXPOSE 3000

CMD [ "node", "dist/main.js" ]

# docker build -f <filename> -t <image-name> .
# example: docker build -f dockerfile.prod -t payments-ms .